import 'package:flutter/material.dart';

class ProjectIconCategory {
  const ProjectIconCategory({required this.label, required this.keys});

  final String label;
  final List<String> keys;
}

class ProjectIconRegistry {
  const ProjectIconRegistry._();

  static const Map<String, IconData> icons = <String, IconData>{
    'rocket': Icons.rocket_launch_outlined,
    'zap': Icons.bolt_outlined,
    'cpu': Icons.memory_outlined,
    'code': Icons.code_outlined,
    'code-2': Icons.data_object_outlined,
    'terminal': Icons.terminal_outlined,
    'bug': Icons.bug_report_outlined,
    'git-branch': Icons.account_tree_outlined,
    'git-pull-request': Icons.merge_type_outlined,
    'server': Icons.dns_outlined,
    'cloud': Icons.cloud_outlined,
    'database': Icons.storage_outlined,
    'hard-drive': Icons.save_outlined,
    'wrench': Icons.build_outlined,
    'hammer': Icons.hardware_outlined,
    'cog': Icons.settings_suggest_outlined,
    'settings': Icons.settings_outlined,
    'wifi': Icons.wifi_outlined,
    'package': Icons.inventory_2_outlined,
    'box': Icons.check_box_outline_blank_outlined,
    'boxes': Icons.all_inbox_outlined,
    'smartphone': Icons.smartphone_outlined,
    'tablet': Icons.tablet_mac_outlined,
    'laptop': Icons.laptop_mac_outlined,
    'monitor': Icons.desktop_windows_outlined,
    'app-window': Icons.web_asset_outlined,
    'mouse-pointer-2': Icons.ads_click_outlined,
    'layers': Icons.layers_outlined,
    'component': Icons.widgets_outlined,
    'puzzle': Icons.extension_outlined,
    'blocks': Icons.view_module_outlined,
    'message-circle': Icons.chat_bubble_outline,
    'message-square': Icons.mode_comment_outlined,
    'megaphone': Icons.campaign_outlined,
    'mail': Icons.mail_outline,
    'inbox': Icons.inbox_outlined,
    'send': Icons.send_outlined,
    'bell': Icons.notifications_none_outlined,
    'users': Icons.group_outlined,
    'users-round': Icons.groups_outlined,
    'user': Icons.person_outline,
    'handshake': Icons.handshake_outlined,
    'speech': Icons.record_voice_over_outlined,
    'phone': Icons.phone_outlined,
    'headphones': Icons.headphones_outlined,
    'palette': Icons.palette_outlined,
    'brush': Icons.brush_outlined,
    'pen-tool': Icons.edit_outlined,
    'pencil': Icons.drive_file_rename_outline,
    'shapes': Icons.category_outlined,
    'sparkles': Icons.auto_awesome_outlined,
    'wand-2': Icons.auto_fix_high_outlined,
    'image': Icons.image_outlined,
    'frame': Icons.crop_free_outlined,
    'swatch-book': Icons.color_lens_outlined,
    'paintbrush': Icons.format_paint_outlined,
    'chart-line': Icons.show_chart_outlined,
    'chart-bar': Icons.bar_chart_outlined,
    'chart-pie': Icons.pie_chart_outline,
    'chart-area': Icons.area_chart_outlined,
    'chart-column': Icons.stacked_bar_chart_outlined,
    'trending-up': Icons.trending_up_outlined,
    'activity': Icons.monitor_heart_outlined,
    'flask-conical': Icons.science_outlined,
    'microscope': Icons.biotech_outlined,
    'telescope': Icons.travel_explore_outlined,
    'binary': Icons.pin_outlined,
    'sigma': Icons.functions_outlined,
    'target': Icons.gps_fixed_outlined,
    'flag': Icons.flag_outlined,
    'compass': Icons.explore_outlined,
    'map': Icons.map_outlined,
    'map-pin': Icons.location_on_outlined,
    'calendar': Icons.calendar_month_outlined,
    'calendar-check': Icons.event_available_outlined,
    'calendar-clock': Icons.more_time_outlined,
    'clipboard-list': Icons.assignment_outlined,
    'list-checks': Icons.checklist_outlined,
    'check-circle': Icons.check_circle_outline,
    'circle-check': Icons.task_alt_outlined,
    'trophy': Icons.emoji_events_outlined,
    'medal': Icons.military_tech_outlined,
    'award': Icons.workspace_premium_outlined,
    'briefcase': Icons.work_outline,
    'briefcase-business': Icons.business_center_outlined,
    'building': Icons.apartment_outlined,
    'store': Icons.storefront_outlined,
    'shopping-cart': Icons.shopping_cart_outlined,
    'shopping-bag': Icons.shopping_bag_outlined,
    'credit-card': Icons.credit_card_outlined,
    'wallet': Icons.account_balance_wallet_outlined,
    'dollar-sign': Icons.attach_money_outlined,
    'badge-dollar': Icons.price_check_outlined,
    'receipt': Icons.receipt_long_outlined,
    'coins': Icons.paid_outlined,
    'book-open': Icons.menu_book_outlined,
    'book': Icons.book_outlined,
    'notebook': Icons.article_outlined,
    'notebook-pen': Icons.edit_note_outlined,
    'file-text': Icons.description_outlined,
    'files': Icons.file_copy_outlined,
    'newspaper': Icons.newspaper_outlined,
    'library': Icons.local_library_outlined,
    'graduation-cap': Icons.school_outlined,
    'lightbulb': Icons.lightbulb_outline,
    'brain': Icons.psychology_outlined,
    'shield': Icons.shield_outlined,
    'shield-check': Icons.verified_user_outlined,
    'lock': Icons.lock_outline,
    'key': Icons.key_outlined,
    'fingerprint': Icons.fingerprint_outlined,
    'eye': Icons.visibility_outlined,
    'scan': Icons.document_scanner_outlined,
    'sprout': Icons.spa_outlined,
    'leaf': Icons.energy_savings_leaf_outlined,
    'tree': Icons.park_outlined,
    'flower': Icons.local_florist_outlined,
    'flame': Icons.local_fire_department_outlined,
    'droplet': Icons.water_drop_outlined,
    'snowflake': Icons.ac_unit_outlined,
    'sun': Icons.wb_sunny_outlined,
    'moon': Icons.dark_mode_outlined,
    'cloudy': Icons.cloud_queue_outlined,
    'mountain': Icons.terrain_outlined,
    'waves': Icons.waves_outlined,
    'wind': Icons.air_outlined,
    'heart': Icons.favorite_border,
    'star': Icons.star_border,
    'gift': Icons.card_giftcard_outlined,
    'gem': Icons.diamond_outlined,
    'crown': Icons.emoji_events_outlined,
    'party-popper': Icons.celebration_outlined,
    'music': Icons.music_note_outlined,
    'camera': Icons.photo_camera_outlined,
    'bookmark': Icons.bookmark_border,
    'anchor': Icons.anchor_outlined,
    'infinity': Icons.all_inclusive_outlined,
    'orbit': Icons.blur_circular_outlined,
    'atom': Icons.hub_outlined,
    'globe': Icons.public_outlined,
    'feather': Icons.draw_outlined,
  };

  static const List<ProjectIconCategory> categories = <ProjectIconCategory>[
    ProjectIconCategory(
      label: 'Engineering',
      keys: <String>[
        'rocket',
        'zap',
        'cpu',
        'code',
        'code-2',
        'terminal',
        'bug',
        'git-branch',
        'git-pull-request',
        'server',
        'cloud',
        'database',
        'hard-drive',
        'wrench',
        'hammer',
        'cog',
        'settings',
        'wifi',
      ],
    ),
    ProjectIconCategory(
      label: 'Product',
      keys: <String>[
        'package',
        'box',
        'boxes',
        'smartphone',
        'tablet',
        'laptop',
        'monitor',
        'app-window',
        'mouse-pointer-2',
        'layers',
        'component',
        'puzzle',
        'blocks',
      ],
    ),
    ProjectIconCategory(
      label: 'Communication',
      keys: <String>[
        'message-circle',
        'message-square',
        'megaphone',
        'mail',
        'inbox',
        'send',
        'bell',
        'users',
        'users-round',
        'user',
        'handshake',
        'speech',
        'phone',
        'headphones',
      ],
    ),
    ProjectIconCategory(
      label: 'Design',
      keys: <String>[
        'palette',
        'brush',
        'pen-tool',
        'pencil',
        'shapes',
        'sparkles',
        'wand-2',
        'image',
        'frame',
        'swatch-book',
        'paintbrush',
      ],
    ),
    ProjectIconCategory(
      label: 'Data & Research',
      keys: <String>[
        'chart-line',
        'chart-bar',
        'chart-pie',
        'chart-area',
        'chart-column',
        'trending-up',
        'activity',
        'flask-conical',
        'microscope',
        'telescope',
        'binary',
        'sigma',
      ],
    ),
    ProjectIconCategory(
      label: 'Goals & Planning',
      keys: <String>[
        'target',
        'flag',
        'compass',
        'map',
        'map-pin',
        'calendar',
        'calendar-check',
        'calendar-clock',
        'clipboard-list',
        'list-checks',
        'check-circle',
        'circle-check',
        'trophy',
        'medal',
        'award',
      ],
    ),
    ProjectIconCategory(
      label: 'Business',
      keys: <String>[
        'briefcase',
        'briefcase-business',
        'building',
        'store',
        'shopping-cart',
        'shopping-bag',
        'credit-card',
        'wallet',
        'dollar-sign',
        'badge-dollar',
        'receipt',
        'coins',
      ],
    ),
    ProjectIconCategory(
      label: 'Knowledge',
      keys: <String>[
        'book-open',
        'book',
        'notebook',
        'notebook-pen',
        'file-text',
        'files',
        'newspaper',
        'library',
        'graduation-cap',
        'lightbulb',
        'brain',
      ],
    ),
    ProjectIconCategory(
      label: 'Security',
      keys: <String>[
        'shield',
        'shield-check',
        'lock',
        'key',
        'fingerprint',
        'eye',
        'scan',
      ],
    ),
    ProjectIconCategory(
      label: 'Nature',
      keys: <String>[
        'sprout',
        'leaf',
        'tree',
        'flower',
        'flame',
        'droplet',
        'snowflake',
        'sun',
        'moon',
        'cloudy',
        'mountain',
        'waves',
        'wind',
      ],
    ),
    ProjectIconCategory(
      label: 'More',
      keys: <String>[
        'heart',
        'star',
        'gift',
        'gem',
        'crown',
        'party-popper',
        'music',
        'camera',
        'bookmark',
        'anchor',
        'infinity',
        'orbit',
        'atom',
        'globe',
        'feather',
      ],
    ),
  ];

  static List<String> get keys => icons.keys.toList(growable: false);

  static IconData? resolve(String? key) {
    if (key == null || key.isEmpty) {
      return null;
    }
    return icons[key];
  }
}
